export const LOGIN_USER_SUCCESS = "USER_LOGIN_SUCCESS";
export const LOGOUT_USER = "USER_LOGOUT";
export const SELECT_PROGRAM = "USER_SELECT_PROGRAM";
export const SELECT_ACADEMIC_YEAR = "USER_SELECT_ACADEMIC_YEAR";
export const USER_CHANGE_PROFILE_PHOTO = "USER_CHANGE_PROFILE_PHOTO";
export const SUPER_ADMIN_SELECT_ORGANIZATION = "SUPER_ADMIN_SELECT_ORGANIZATION";
export const SUPER_ADMIN_UPDATE_ORGANIZATION = "SUPER_ADMIN_UPDATE_ORGANIZATION";
