export const LOGIN_USER_SUCCESS = "RMS_USER_LOGIN_SUCCESS";
export const LOGOUT_USER = "RMS_USER_LOGOUT";
export const SELECT_PROGRAM = "RMS_USER_SELECT_PROGRAM";
export const SELECT_ACADEMIC_YEAR = "RMS_USER_SELECT_ACADEMIC_YEAR";
export const USER_CHANGE_PROFILE_PHOTO = "USER_CHANGE_PROFILE_PHOTO";
export const SUPER_ADMIN_SELECT_INSTITUTE = "RMS_SUPER_ADMIN_SELECT_INSTITUTE";
export const SUPER_ADMIN_UPDATE_INSTITUTE = "RMS_SUPER_ADMIN_UPDATE_INSTITUTE";
